on:
  release:
    types:
      - published

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Download release asset
        run: |
          wget ${{ github.event.release.assets[0].browser_download_url }}

      - name: Upload to Modrinth
        uses: Kir-Antipov/mrpack-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project-id: ea2V0WBF
          files: |
            *.mrpack
